services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json

  veiculo:
    build: ./veiculo
    container_name: veiculo
    depends_on:
      - server
    environment:
      - PLACA=NAY00235
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    stdin_open: true
    tty: true

  #veiculo2:
   # build: ./veiculo
    #container_name: veiculo2
    #depends_on:
     # - server
    #environment:
    #  - ID-VEICULO=2
    #volumes:
     # - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      #- ./dados/dadosVeiculos.json:/app/dadosVeiculos.json

  #veiculo3:
  #  build: ./veiculo
   # container_name: veiculo3
    #depends_on:
     # - server
    #environment:
    #  - ID-VEICULO=3
    #volumes:
     # - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      #- ./dados/dadosVeiculos.json:/app/dadosVeiculos.json

  #veiculo4:
  #  build: ./veiculo
   # container_name: veiculo4
    #depends_on:
     # - server
    #environment:
    #  - ID-VEICULO=4
    #volumes:
     # - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      #- ./dados/dadosVeiculos.json:/app/dadosVeiculos.json

  #veiculo5:
   # build: ./veiculo
    #container_name: veiculo5
    #depends_on:
     # - server
    #environment:
    #  - ID-VEICULO=5
    #volumes:
     # - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      #- ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
  
  ponto:
    build: ./ponto
    container_name: ponto
    depends_on:
      - server
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
    environment:
      - ID-PONTO=1

  #ponto2:
   # build: ./ponto
    #container_name: ponto2
    #depends_on:
     # - server
    #environment:
    #  - ID-PONTO=2
