services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json

  veiculo:
    build: ./veiculo
    container_name: veiculo
    depends_on:
      - server
    environment:
      - PLACA=MUQ9437
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    stdin_open: true
    tty: true
  
  veiculo2:
    build: ./veiculo
    container_name: veiculo2
    depends_on:
      - server
    environment:
      - PLACA=DYJ3211
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    stdin_open: true
    tty: true

  veiculo3:
    build: ./veiculo
    container_name: veiculo3
    depends_on:
      - server
    environment:
      - PLACA=MXB4354
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    stdin_open: true
    tty: true

  veiculo4:
    build: ./veiculo
    container_name: veiculo4
    depends_on:
      - server
    environment:
      - PLACA=KFM4784
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    stdin_open: true
    tty: true

  veiculo5:
    build: ./veiculo
    container_name: veiculo5
    depends_on:
      - server
    environment:
      - PLACA=FBK4493
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    stdin_open: true
    tty: true
  
  ponto:
    build: ./ponto
    container_name: ponto
    depends_on:
      - server
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/contasUsuarios.json:/app/contasUsuarios.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    environment:
      - ID-PONTO=1
    stdin_open: true
    tty: true

  ponto2:
    build: ./ponto
    container_name: ponto2
    depends_on:
      - server
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/contasUsuarios.json:/app/contasUsuarios.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    environment:
      - ID-PONTO=2
    stdin_open: true
    tty: true 
  
  ponto3:
    build: ./ponto
    container_name: ponto3
    depends_on:
      - server
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/contasUsuarios.json:/app/contasUsuarios.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    environment:
      - ID-PONTO=3
    stdin_open: true
    tty: true 
  
  ponto4:
    build: ./ponto
    container_name: ponto4
    depends_on:
      - server
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/contasUsuarios.json:/app/contasUsuarios.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    environment:
      - ID-PONTO=4
    stdin_open: true
    tty: true 

  ponto5:
    build: ./ponto
    container_name: ponto5
    depends_on:
      - server
    volumes:
      - ./dados/MapaDeFeira.csv:/app/MapaDeFeira.csv
      - ./dados/dadosVeiculos.json:/app/dadosVeiculos.json
      - ./dados/contasUsuarios.json:/app/contasUsuarios.json
      - ./dados/dadosPontos.json:/app/dadosPontos.json
    environment:
      - ID-PONTO=5
    stdin_open: true
    tty: true 

